# Generated by Django 5.0.4 on 2024-04-25 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spaceport", "0003_alter_route_destination_alter_route_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spaceflight",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="route",
                to="spaceport.route",
            ),
        ),
        migrations.AlterField(
            model_name="spaceflight",
            name="spaceship",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spaceship",
                to="spaceport.spaceship",
            ),
        ),
    ]
