# Generated by Django 5.0.4 on 2024-04-25 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spaceport", "0004_alter_spaceflight_route_alter_spaceflight_spaceship"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="spaceflight",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="spaceport.spaceflight"
            ),
        ),
        migrations.AddIndex(
            model_name="route",
            index=models.Index(
                fields=["source", "destination"], name="spaceport_r_source__15d603_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="route",
            index=models.Index(
                fields=["source"], name="spaceport_r_source__484601_idx"
            ),
        ),
    ]
